# Generated by Django 5.0.4 on 2024-04-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default=1, max_length=35, verbose_name='Название продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_warehouse', to='products.warehouse', verbose_name='Название продукта'),
        ),
    ]
