# Generated by Django 5.0.4 on 2024-04-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_manufacturer_remove_warehouse_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping_cart',
            options={'verbose_name': 'Корзина покупки', 'verbose_name_plural': 'Корина покупок'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_product', to='products.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='total_product',
            field=models.IntegerField(verbose_name='Общая стоимость покупки'),
        ),
    ]
