# Generated by Django 5.0.4 on 2024-04-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_shopping_cart_options_remove_product_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='cost_product',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='total_product',
        ),
    ]
