# Generated by Django 5.0.4 on 2024-08-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_сountry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сountry',
            new_name='Country',
        ),
    ]
