# Generated by Django 5.0.4 on 2024-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_city_alter_country_managers_remove_country_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название страны'),
        ),
    ]
